@startuml
	class Tweet {

	}

	class Profile {

	}

	class TargetingProfile {

	}
	
	class InfluenceProfile {

	}

	class ImpactProfile {

	}

	class ActivityProfile {

	}

	class ProfileDataEntry {

	}

	class TwitterLink {

	}

	class KnownLocation {

	}

	class KnownClient {

	}

	class TermOccurrence {

	}
	
	class TwitterCluster {

	}

	class TwitterTouch {

	}

	class Domain {

	}

	class DomainTerm {

	}

	' twitter facts
	Tweet <-- Profile : belongs-to

	' user graph
	TwitterLink --> Profile : first
	TwitterLink --> Profile : second
	TwitterTouch --> Profile : first
	TwitterTouch --> Profile : second
	TwitterCluster -- Profile : < belongs

	' user stalk
	Profile "1" *--> "*" KnownLocation
	Profile "1" *--> "*" KnownClient

	' basic sentiment analysis
	Domain o--> DomainTerm
	DomainTerm <-- TermOccurrence
	TermOccurrence --> Profile

	' metrics
	Profile "*" -- "*" ImpactProfile
	ImpactProfile "*" -- "1" Domain
	ImpactProfile *--> "*" ProfileDataEntry

	Profile "*" -- "*" InfluenceProfile
	InfluenceProfile "*" -- "1" TwitterCluster
	InfluenceProfile *--> "*" ProfileDataEntry

	Profile "1" -- "1" TargetingProfile
	TargetingProfile *--> "*" ProfileDataEntry

	Profile "1" -- "1" ActivityProfile
	ActivityProfile *--> "*" ProfileDataEntry  

@enduml