@startuml
left to right direction

	class Profile {

	}

	package facts {

		class Tweet {

		}

		Tweet <-- Profile : belongs-to
	}

	package graph {

		class TwitterLink {

		}

		class TwitterCluster {

		}

		class TwitterTouch {

		}


		TwitterLink --> Profile : first
		TwitterLink --> Profile : second
		TwitterTouch --> Profile : first
		TwitterTouch --> Profile : second
		TwitterCluster -- Profile : < belongs
	}

	package habits {

		class KnownLocation {

		}

		class KnownClient {

		}

		Profile "1" *--> "*" KnownLocation
		Profile "1" *--> "*" KnownClient
	}

	package sentiment-analysis {

		class Domain {

		}

		class DomainTerm {

		}

		class TermOccurrence {

		}

		Domain o--> DomainTerm
		DomainTerm <-- TermOccurrence
		TermOccurrence --> Profile
	}

	package metrics {

		class TargetingProfile {

		}
		
		class InfluenceProfile {

		}

		class ImpactProfile {

		}

		class ActivityProfile {

		}

		class ProfileDataEntry {

		}

		Profile "*" -- "*" ImpactProfile
		ImpactProfile "*" -- "1" Domain
		ImpactProfile *--> "*" ProfileDataEntry

		Profile "*" -- "*" InfluenceProfile
		InfluenceProfile "*" -- "1" TwitterCluster
		InfluenceProfile *--> "*" ProfileDataEntry

		Profile "1" -- "1" TargetingProfile
		TargetingProfile *--> "*" ProfileDataEntry

		Profile "1" -- "1" ActivityProfile
		ActivityProfile *--> "*" ProfileDataEntry 
	} 

@enduml